# -*- coding: utf-8 -*-
"""
rutas_oficiales.py (botv2)
----------------------------
Fuente de verdad: cada ruta oficial (identificada de forma UNICA por
codigo+grupo, ya que algunos codigos se repiten entre grupos con
recorridos distintos) y el conjunto de paradas por las que pasa.

Transcrito directamente de los mapas oficiales de la Gobernacion de
Monagas / Alcaldia de Maturin ("MAPA DE RUTAS - Grupo 1" a "Grupo 5").
"""

RUTAS_OFICIALES = {
    "1 UDO||G4": {"codigo": "1 UDO", "grupo": 4, "etiqueta": "1 UDO", "paradas": ["Ambulatorio", "Av. El Ejercito", "Av. Libertador", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Liceo Francisco Isnardi", "Los Guaritos", "Pollo El Más Grande", "UDO", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "110||G4": {"codigo": "110", "grupo": 4, "etiqueta": "110", "paradas": ["Av. Bella Vista", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "La Carbonera", "La Cruz", "Liceo Francisco Isnardi", "Pollo El Más Grande", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "12-14||G1": {"codigo": "12-14", "grupo": 1, "etiqueta": "12-14 (Grupo 1)", "paradas": ["Aeropuerto", "Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "Frente a Génesis", "Frente a MEMCA", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "SAIME", "Torre Coffel"]},
    "12-14||G5": {"codigo": "12-14", "grupo": 5, "etiqueta": "12-14 (Grupo 5)", "paradas": ["C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Guireñita", "La Libertad", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken", "Urb. José Tadeo Monagas"]},
    "15||G2": {"codigo": "15", "grupo": 2, "etiqueta": "15 (Grupo 2)", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. R. Gallegos", "Av. Raúl Leoni", "C.C. Victoria", "El Parquecito", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Florecita", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "15||G4": {"codigo": "15", "grupo": 4, "etiqueta": "15 (Grupo 4)", "paradas": ["A. José de Sucre", "Av. José A. Páez (J. A. Páez)", "Calle del Hambre II", "Campo Ayacucho", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "La Muralla", "Liceo Francisco Isnardi", "Pollo El Más Grande", "R. Los 3 Elefantes", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "16||G2": {"codigo": "16", "grupo": 2, "etiqueta": "16 (Grupo 2)", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. R. Gallegos", "Av. Raúl Leoni", "C.C. Victoria", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Florecita", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "Sabana Grande", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "16||G4": {"codigo": "16", "grupo": 4, "etiqueta": "16 (Grupo 4)", "paradas": ["Amb. Vargas", "Av. El Ejercito", "Av. Libertador", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Complejo Paramaconi", "Farma Expres", "Frente al Mercal de la UBV", "Liceo Francisco Isnardi", "Pollo El Más Grande", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "17||G5": {"codigo": "17", "grupo": 5, "etiqueta": "17", "paradas": ["C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Cruz", "La Guireñita", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken", "San Jaime", "Zona Industrial"]},
    "18||G2": {"codigo": "18", "grupo": 2, "etiqueta": "18 (Grupo 2)", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. Raúl Leoni", "C.C. Victoria", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Florecita", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "Mereyal", "Sabana Grande", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "18||G4": {"codigo": "18", "grupo": 4, "etiqueta": "18 (Grupo 4)", "paradas": ["Av. José A. Páez (J. A. Páez)", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Complejo Paramaconi", "Farma Expres", "Frente al Mercal de la UBV", "La Florida", "La Murallita", "Liceo Francisco Isnardi", "Los Pinos", "Pollo El Más Grande", "Terminal", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "19-22||G1": {"codigo": "19-22", "grupo": 1, "etiqueta": "19-22 (Grupo 1)", "paradas": ["Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "Frente a Génesis", "Frente a MEMCA", "Las Cocuizas", "Los Cortijos", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel"]},
    "19-22||G5": {"codigo": "19-22", "grupo": 5, "etiqueta": "19-22 (Grupo 5)", "paradas": ["Alto Paramaconi", "Av. Bella Vista", "C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Guireñita", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken"]},
    "1||G1": {"codigo": "1", "grupo": 1, "etiqueta": "1 (Grupo 1)", "paradas": ["Av. Raúl Leoni", "Campo Alegre", "Comercial Cobby", "Dragón Chino", "El Silencio", "Frente a Génesis", "Frente a MEMCA", "Las Cocuizas", "Los Cortijos", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel"]},
    "1||G4": {"codigo": "1", "grupo": 4, "etiqueta": "1 (Grupo 4)", "paradas": ["Av. El Ejercito", "Av. Libertador", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Las Comunales (El Comunales)", "Liceo Francisco Isnardi", "Los Godos", "Pollo El Más Grande", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "20||G3": {"codigo": "20", "grupo": 3, "etiqueta": "20 (Grupo 3)", "paradas": ["Antigua Librería Nacional", "Av. Raúl Leoni", "C.C. La Cascada", "Frente a Hospital Universitario Manuel Núñez Tovar", "Frente al Banco de Venezuela", "Frente antigua Guireñita II", "Parare", "Pedagógico", "Perfumes Factory (DETRÁS DE LA GOBERNACIÓN)", "Plaza Mayor", "Santa Inés", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "20||G4": {"codigo": "20", "grupo": 4, "etiqueta": "20 (Grupo 4)", "paradas": ["Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Esc. Apolinar Cantor", "Farma Expres", "Frente al Mercal de la UBV", "Liceo Francisco Isnardi", "Los Guaritos", "Pollo El Más Grande", "Ppal. Fundemos", "Ppal. La Puente", "Terminal", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "21-28||G3": {"codigo": "21-28", "grupo": 3, "etiqueta": "21-28", "paradas": ["Antigua Librería Nacional", "Av. La Paz", "Av. Raúl Leoni", "Frente a Hospital Universitario Manuel Núñez Tovar", "Frente al Banco de Venezuela", "Frente antigua Guireñita II", "Perfumes Factory (DETRÁS DE LA GOBERNACIÓN)", "Plaza Mayor", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "21||G5": {"codigo": "21", "grupo": 5, "etiqueta": "21", "paradas": ["C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Cruz", "La Guireñita", "Las Cayenas", "Las Garzas", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken", "Villas Alta Cruz"]},
    "28||G5": {"codigo": "28", "grupo": 5, "etiqueta": "28", "paradas": ["C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Cruz", "La Guireñita", "Las Carolinas", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken", "Zona Industrial"]},
    "30-Coop. 3||G5": {"codigo": "30-Coop. 3", "grupo": 5, "etiqueta": "30-Coop. 3", "paradas": ["C. Ding Dong", "Calle Principal Alto Paramaconi", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Guireñita", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken", "San Rafael", "Terrazas", "Urb. José Tadeo Monagas"]},
    "32||G3": {"codigo": "32", "grupo": 3, "etiqueta": "32 (Grupo 3)", "paradas": ["Antigua Librería Nacional", "Av. Raúl Leoni", "Frente a Hospital Universitario Manuel Núñez Tovar", "Frente al Banco de Venezuela", "Frente antigua Guireñita II", "Parque Andrés Eloy Blanco", "Pedagógico", "Perfumes Factory (DETRÁS DE LA GOBERNACIÓN)", "Plaza Mayor", "San Judas Tadeo", "UBV (FRENTE REST. PALACIO IMPERIAL)", "Valenzuela"]},
    "32||G5": {"codigo": "32", "grupo": 5, "etiqueta": "32 (Grupo 5)", "paradas": ["Av. Bella Vista", "Aves del Paraíso", "C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Cruz", "La Guireñita", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken", "Zona Industrial"]},
    "33||G3": {"codigo": "33", "grupo": 3, "etiqueta": "33 (Grupo 3)", "paradas": ["Antigua Librería Nacional", "Av. Raúl Leoni", "Frente a Hospital Universitario Manuel Núñez Tovar", "Frente al Banco de Venezuela", "Frente antigua Guireñita II", "Parque Andrés Eloy Blanco", "Pedagógico", "Perfumes Factory (DETRÁS DE LA GOBERNACIÓN)", "Plaza Mayor", "San Judas Tadeo", "UBV (FRENTE REST. PALACIO IMPERIAL)", "Valenzuela"]},
    "33||G5": {"codigo": "33", "grupo": 5, "etiqueta": "33 (Grupo 5)", "paradas": ["Av. Bella Vista", "C. Ding Dong", "Center Muebles", "Comercial Ganma", "El Samán", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Guanaguaney", "Heladería Darly", "La Cruz", "La Guireñita", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken", "Zona Industrial"]},
    "35||G1": {"codigo": "35", "grupo": 1, "etiqueta": "35 (Grupo 1)", "paradas": ["Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "Frente a Génesis", "Frente a MEMCA", "La Línea", "Las Cocuizas", "Los Cortijos", "Pararí", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel"]},
    "35||G4": {"codigo": "35", "grupo": 4, "etiqueta": "35 (Grupo 4)", "paradas": ["Av. Bicentenario", "Av. Libertador", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Liceo Francisco Isnardi", "Plaza El Indio", "Pollo El Más Grande", "Terminal", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "3||G1": {"codigo": "3", "grupo": 1, "etiqueta": "3", "paradas": ["Av. Alirio Ugarte Pelayo", "Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "Frente a Génesis", "Frente a MEMCA", "Min. Ambiente", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel"]},
    "40||G2": {"codigo": "40", "grupo": 2, "etiqueta": "40 (Grupo 2)", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. Raúl Leoni", "C.C. Victoria", "El Nazareno", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Florecita", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "Sabana Grande", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "40||G4": {"codigo": "40", "grupo": 4, "etiqueta": "40 (Grupo 4)", "paradas": ["Av. Bella Vista", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "La Carbonera", "Liceo Francisco Isnardi", "Pollo El Más Grande", "Retorno distribuidor El Toro Gordo", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "41||G2": {"codigo": "41", "grupo": 2, "etiqueta": "41 (Grupo 2)", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. Raúl Leoni", "C.C. Victoria", "El Nazareno", "El Parquecito", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "Sabana Grande", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "41||G4": {"codigo": "41", "grupo": 4, "etiqueta": "41 (Grupo 4)", "paradas": ["Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Liceo Francisco Isnardi", "Los Godos calles 10, 11 y 13", "Pollo El Más Grande", "Terminal", "U. Nacional Abierta", "U.E. A. Rengel", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "46-55-56-57||G4": {"codigo": "46-55-56-57", "grupo": 4, "etiqueta": "46-55-56-57", "paradas": ["A. José de Sucre", "Av. José A. Páez (J. A. Páez)", "Calle del Hambre II", "Campo Ayacucho", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "La Muralla", "Liceo Francisco Isnardi", "Pollo El Más Grande", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "46||G2": {"codigo": "46", "grupo": 2, "etiqueta": "46", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. Raúl Leoni", "C.C. Victoria", "El Parquecito", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Florecita", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "UBV (FRENTE REST. PALACIO IMPERIAL)", "UDO Juanico"]},
    "47||G1": {"codigo": "47", "grupo": 1, "etiqueta": "47", "paradas": ["Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "ETAR", "Frente a Génesis", "Frente a MEMCA", "Las Cocuizas", "Los Cortijos", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Psiquiátrico", "Torre Coffel"]},
    "51||G3": {"codigo": "51", "grupo": 3, "etiqueta": "51 (Grupo 3)", "paradas": ["Antigua Librería Nacional", "Av. Raúl Leoni", "Frente a Hospital Universitario Manuel Núñez Tovar", "Frente al Banco de Venezuela", "Frente antigua Guireñita II", "Parque Andrés Eloy Blanco", "Pedagógico", "Perfumes Factory (DETRÁS DE LA GOBERNACIÓN)", "Plaza Mayor", "San Judas Tadeo", "UBV (FRENTE REST. PALACIO IMPERIAL)", "Valenzuela"]},
    "51||G5": {"codigo": "51", "grupo": 5, "etiqueta": "51 (Grupo 5)", "paradas": ["C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Cruz", "La Guireñita", "Las Cayenas", "Las Garzas", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken"]},
    "55||G2": {"codigo": "55", "grupo": 2, "etiqueta": "55", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. Raúl Leoni", "B. del Aeropuerto", "C.C. Victoria", "El Parquecito", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "UBV (FRENTE REST. PALACIO IMPERIAL)", "UDO Juanico"]},
    "56||G2": {"codigo": "56", "grupo": 2, "etiqueta": "56", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. Raúl Leoni", "B. del Aeropuerto", "C.C. Victoria", "El Parquecito", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "UBV (FRENTE REST. PALACIO IMPERIAL)", "UDO Juanico"]},
    "57||G2": {"codigo": "57", "grupo": 2, "etiqueta": "57", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. Raúl Leoni", "B. del Aeropuerto", "C.C. Victoria", "El Parquecito", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "UBV (FRENTE REST. PALACIO IMPERIAL)", "UDO Juanico"]},
    "58-59-84||G4": {"codigo": "58-59-84", "grupo": 4, "etiqueta": "58-59-84", "paradas": ["Av. Bicentenario", "Av. Bolívar", "Av. Libertador", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Liceo Francisco Isnardi", "Plaza El Indio", "Pollo El Más Grande", "Terminal", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "58||G2": {"codigo": "58", "grupo": 2, "etiqueta": "58", "paradas": ["Amb. Concepción Mariño (PLAZA PIAR)", "Av. R. Gallegos", "Av. Raúl Leoni", "C.C. Victoria", "Farma Paz (ANTIGUA CITY LAMP)", "Frente a la entrada Las Casitas HUMNT", "Frente al Isnardi", "La Floresta", "La Preferida (DETRÁS DE LA GOBERNACIÓN)", "Las Flores", "Las Trinitarias", "Los Tapiales II", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "59||G1": {"codigo": "59", "grupo": 1, "etiqueta": "59", "paradas": ["Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "Frente a Génesis", "Frente a MEMCA", "Las Cocuizas", "Los Cortijos", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel", "Urb. Andrés Eloy Blanco"]},
    "5||G1": {"codigo": "5", "grupo": 1, "etiqueta": "5 (Grupo 1)", "paradas": ["1º de Mayo", "Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "El Silencio", "Frente a Génesis", "Frente a MEMCA", "Las Cocuizas", "Los Cortijos", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel"]},
    "5||G4": {"codigo": "5", "grupo": 4, "etiqueta": "5 (Grupo 4)", "paradas": ["Av. Juncal", "Av. Libertador", "Barrio Morichal", "Calle La Planta", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Liceo Francisco Isnardi", "Mercado", "Negro Primero", "Pollo El Más Grande", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "6||G3": {"codigo": "6", "grupo": 3, "etiqueta": "6 (Grupo 3)", "paradas": ["Antigua Librería Nacional", "Av. Raúl Leoni", "C.C. La Cascada", "Frente a Hospital Universitario Manuel Núñez Tovar", "Frente al Banco de Venezuela", "Frente antigua Guireñita II", "Pedagógico", "Perfumes Factory (DETRÁS DE LA GOBERNACIÓN)", "Plaza Mayor", "Santa Inés", "UBV (FRENTE REST. PALACIO IMPERIAL)", "Urb. Lomas del Viento"]},
    "6||G4": {"codigo": "6", "grupo": 4, "etiqueta": "6 (Grupo 4)", "paradas": ["Av. El Ejercito", "Av. Libertador", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Las Comunales (El Comunales)", "Liceo Francisco Isnardi", "Los Godos", "Pollo El Más Grande", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "7||G3": {"codigo": "7", "grupo": 3, "etiqueta": "7 (Grupo 3)", "paradas": ["Antigua Librería Nacional", "Brisas del Orinoco", "Entrada Pinto Salinas", "Frente a Hospital Universitario Manuel Núñez Tovar", "Frente al Banco de Venezuela", "Frente antigua Guireñita II", "Perfumes Factory (DETRÁS DE LA GOBERNACIÓN)", "Plaza Mayor", "UBV (FRENTE REST. PALACIO IMPERIAL)"]},
    "7||G4": {"codigo": "7", "grupo": 4, "etiqueta": "7 (Grupo 4)", "paradas": ["Av. Libertador", "Calle La Planta", "Calle del Hambre II", "Cardiovascular", "Casa Todo", "Comercial WeeKo", "Farma Expres", "Frente al Mercal de la UBV", "Las Comunales (El Comunales)", "Liceo Francisco Isnardi", "Negro Primero", "Pollo El Más Grande", "Zapatería Estrella de Oriente", "Zapatería Jump"]},
    "84||G1": {"codigo": "84", "grupo": 1, "etiqueta": "84", "paradas": ["Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "Frente a Génesis", "Frente a MEMCA", "La Democracia", "Las Cocuizas", "Los Cortijos", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel"]},
    "86||G1": {"codigo": "86", "grupo": 1, "etiqueta": "86 (Grupo 1)", "paradas": ["Antiguo Club Italo", "Av. Cruz Peraza", "Av. Raúl Leoni", "Comercial Cobby", "Dragón Chino", "Frente a Génesis", "Frente a MEMCA", "Plaza Piar (Grupo 1)", "Plaza Rómulo Gallegos", "Torre Coffel"]},
    "86||G5": {"codigo": "86", "grupo": 5, "etiqueta": "86 (Grupo 5)", "paradas": ["Av. Bella Vista", "C. Ding Dong", "Center Muebles", "Comercial Ganma", "Entrada Casitas HUMNT", "Farmatodo", "Fiorpan Bicentenario", "Gitano's Café", "Heladería Darly", "La Cruz", "La Guireñita", "Liceo Miguel J. Sanz", "Liceo Núñez Mares", "Pollo Smart Chicken"]},
}
